name: push-action
on: push

jobs:
    push-job:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: echo hello world
        - name: step2(multiline)
          run: |
              echo hello
              echo world