name: pull-request-workflow
on: 
    pull-request:
        types: [opened]
    
jobs: 
    pull-request-jobs:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: echo hello pull request

        