name: workflow-dispatch
on: workflow_dispatch:
      inputs:
        name:
          description: 'set name'
          required: true
          default: 'junyeong'
          type: string
        environment:
          description: 'env'
          required: true
          default: 'debug'
          type: choice
          options:
          - debug
          - release
          - qa